kind: List
apiVersion: v1
items:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: jupyterhub
      labels:
        build: jupyterhub
    spec:
      lookupPolicy:
        local: true
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: jupyterhub
      labels:
        build: jupyterhub
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
      source:
        type: Git
        git:
          uri: https://github.com/k9nd0/jupyterhub-quickstart.git
          ref: develop
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-38-nodejs-14:latest
      output:
        to:
          kind: ImageStreamTag
          name: jupyterhub:latest
